sudo apt-get -y purge --auto-remove account-plugin-aim account-plugin-facebook 
sudo apt-get -y purge --auto-remove  account-plugin-flickr 
sudo apt-get -y purge --auto-remove  account-plugin-google 
sudo apt-get -y purge --auto-remove  account-plugin-windows-live 
sudo apt-get -y purge --auto-remove  account-plugin-salut   
sudo apt-get -y purge --auto-remove  account-plugin-yahoo  
sudo apt-get -y purge --auto-remove  aisleriot 
sudo apt-get -y purge --auto-remove  default-jdk 
sudo apt-get -y purge --auto-remove  firefox-locale-de 
sudo apt-get -y purge --auto-remove  firefox-locale-es 
sudo apt-get -y purge --auto-remove  firefox-locale-pt 
sudo apt-get -y purge --auto-remove  firefox-locale-zh-hans 
sudo apt-get -y purge --auto-remove  flashplugin-installer 
sudo apt-get -y purge --auto-remove  friends-facebook 
sudo apt-get -y purge --auto-remove  friends-twitter 
sudo apt-get -y purge --auto-remove  gnome-bluetooth 
sudo apt-get -y purge --auto-remove  gnome-mahjongg 
sudo apt-get -y purge --auto-remove  gnome-mines 
sudo apt-get -y purge --auto-remove  gnome-sudoku 
sudo apt-get -y purge --auto-remove  indicator-bluetooth 
sudo apt-get -y purge --auto-remove  landscape-client-ui-install   
sudo apt-get -y purge --auto-remove  language-pack-de 
sudo apt-get -y purge --auto-remove  language-pack-de-base 
sudo apt-get -y purge --auto-remove  language-pack-es 
sudo apt-get -y purge --auto-remove  language-pack-es-base 
sudo apt-get -y purge --auto-remove  language-pack-gnome-de 
sudo apt-get -y purge --auto-remove  language-pack-gnome-de-base 
sudo apt-get -y purge --auto-remove  language-pack-gnome-es 
sudo apt-get -y purge --auto-remove  language-pack-gnome-es-base 
sudo apt-get -y purge --auto-remove  language-pack-gnome-pt 
sudo apt-get -y purge --auto-remove  language-pack-gnome-pt-base 
sudo apt-get -y purge --auto-remove  language-pack-gnome-zh-hans 
sudo apt-get -y purge --auto-remove  language-pack-gnome-zh-hans-base 
sudo apt-get -y purge --auto-remove  language-pack-pt 
sudo apt-get -y purge --auto-remove  language-pack-pt-base 
sudo apt-get -y purge --auto-remove  language-pack-zh-hans 
sudo apt-get -y purge --auto-remove  language-pack-zh-hans-base 
sudo apt-get -y purge --auto-remove  libgnome-bluetooth11 
sudo apt-get -y purge --auto-remove  openjdk-7-jdk 
sudo apt-get -y purge --auto-remove  quadrapassel 
sudo apt-get -y purge --auto-remove  unity-lens-music   
sudo apt-get -y purge --auto-remove  unity-lens-photos 
sudo apt-get -y purge --auto-remove  unity-lens-video   
sudo apt-get -y purge --auto-remove  unity-scope-audacious   
sudo apt-get -y purge --auto-remove  unity-scope-chromiumbookmarks   
sudo apt-get -y purge --auto-remove  unity-scope-clementine   
sudo apt-get -y purge --auto-remove  unity-scope-colourlovers   
sudo apt-get -y purge --auto-remove  unity-scope-devhelp   
sudo apt-get -y purge --auto-remove  unity-scope-firefoxbookmarks   
sudo apt-get -y purge --auto-remove  unity-scope-gmusicbrowser   
sudo apt-get -y purge --auto-remove  unity-scope-gourmet   
sudo apt-get -y purge --auto-remove  unity-scope-guayadeque   
sudo apt-get -y purge --auto-remove  unity-scope-musicstores   
sudo apt-get -y purge --auto-remove  unity-scope-musique   
sudo apt-get -y purge --auto-remove  unity-scope-openclipart   
sudo apt-get -y purge --auto-remove  unity-scope-texdoc   
sudo apt-get -y purge --auto-remove  unity-scope-tomboy   
sudo apt-get -y purge --auto-remove  unity-scope-video-remote   
sudo apt-get -y purge --auto-remove  unity-scope-virtualbox   
sudo apt-get -y purge --auto-remove  unity-scope-zotero   
sudo apt-get -y purge --auto-remove  unity-webapps-common 
sudo apt-get -y purge --auto-remove  gnome-games-common gbrainy 
sudo apt-get -y purge --auto-remove  aisleriot 
sudo apt-get -y purge --auto-remove  gnome-sudoku 
sudo apt-get -y purge --auto-remove  mahjongg 
sudo apt-get -y purge --auto-remove  ace-of-penguins 
sudo apt-get -y purge --auto-remove  gnomine 
sudo apt-get -y purge --auto-remove  kdegames 
sudo apt-get -y purge --auto-remove  brasero 
sudo apt-get -y purge --auto-remove  brasero-cdrkit 
sudo apt-get -y purge --auto-remove  brasero-common 
sudo apt-get -y purge --auto-remove  cheese 
sudo apt-get -y purge --auto-remove  cheese-common

sudo apt-get -y autoremove
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y autoremove